version: '2.3'

services:
  slomo:
    build: .
    command: --sf 3 --video data/videos/car.mp4 --output data/output/slocar.mp4
    volumes:
     - .:/workdir
    ipc: host
    network_mode: host
#    runtime: nvidia

